### ISSUE TITLE
Configure Default Gateway

### ISSUE THREAD

**Issue by LukeOwlclaw** [jpmikkers/DHCPServer#3]
Is it possible to configure a Default Gateway which is published to all clients? Could you provide a sample DHCPServer.exe.config?

**Comment by jpmikkers** [comment]
Hi, it's possible but not very pretty since I never bothered to implement a dedicated config mapping for dhcp option 3, which is the router/gateway option. However, there's a workaround by using the generic config option (see attachment).

On windows, the xml config should be located at c:\ProgramData\JPMikkers\DHCP Server\Configuration.xml

[Configuration.zip](https://github.com/jpmikkers/DHCPServer/files/1026234/Configuration.zip)

**Comment by jpmikkers** [comment]
I've added direct support for this option, add the following OptionConfiguration to the Options tag:

```xml
    ....
    <Options>
      <OptionConfiguration xsi:type="OptionConfigurationRouter">
        <Mode>Default</Mode>
        <Addresses>
          <Address>10.20.30.40</Address>
        </Addresses>
      </OptionConfiguration>
    ....
```

**Comment by ncnnnnn** [comment]
OptionConfigurationGeneric dns1 = new OptionConfigurationGeneric();
  dns1.Option = 6;
  dns1.Data = "08 08 08 08 08 08 04 04";
  options.Add(dns1.ConstructOptionItem());
   

  m_Server.Options = options;

add dns
